### ISSUE TITLE
About the 'label' field in the train dataset

### ISSUE THREAD

**Issue by jin210625** [jaychempan/PIR#4]
您好，我想问一下 finetune 数据集中的 label 字段是怎么从原始数据中提取出来的，有参考资料或者代码吗？

**Comment by jaychempan** [comment]
思路就是从RSITMD和RSICD中image的名称中提取的label，写到fintune的json文件中，处理的代码已经找不到了

**Comment by jaychempan** [comment]
> 您好，我想问一下 finetune 数据集中的 label 字段是怎么从原始数据中提取出来的，有参考资料或者代码吗？

处理的代码已经找不到了，思路就是从RSITMD和RSICD中image的名称中提取的label，写到fintune的json文件中

**Comment by jin210625** [comment]
好的，感谢回复
